# Generated by Django 4.1.13 on 2024-07-14 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('diabetes_risk', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_glucose', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('bmi', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('nutrients', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MealRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateTimeField()),
                ('avg_blood_glucose', models.FloatField()),
                ('avg_blood_pressure', models.CharField(max_length=20)),
                ('avg_calories', models.FloatField()),
                ('avg_bmi', models.FloatField()),
                ('weight_increase', models.FloatField()),
                ('monthly_risk', models.FloatField()),
                ('overall_health_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress_level', models.IntegerField()),
                ('physical_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.physicalactivity')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=20)),
                ('height', models.FloatField()),
                ('birthdate', models.DateField()),
                ('family_history', models.BooleanField()),
                ('profile_picture', models.CharField(max_length=255)),
                ('user_notification', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('daily_records', models.ManyToManyField(to='api.dailyrecord')),
                ('health_records', models.ManyToManyField(to='api.healthrecords')),
                ('meal_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mealrecommendation')),
                ('monthly_records', models.ManyToManyField(to='api.monthlyrecord')),
                ('physical_records', models.ManyToManyField(to='api.physicalrecords')),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.preferences')),
            ],
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='health_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.healthrecords'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='meals',
            field=models.ManyToManyField(to='api.meal'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='physical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.physicalrecords'),
        ),
    ]
