# Generated by Django 4.1.13 on 2024-07-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_records',
        ),
        migrations.RemoveField(
            model_name='user',
            name='meal_recommendation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='monthly_records',
        ),
        migrations.RemoveField(
            model_name='user',
            name='physical_records',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_notification',
        ),
        migrations.AddField(
            model_name='healthrecords',
            name='diabetes_risk',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='health_records',
            field=models.ManyToManyField(blank=True, to='api.healthrecords'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.preferences'),
        ),
    ]
