# Generated by Django 4.1.13 on 2024-07-16 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('avg_blood_glucose', models.FloatField()),
                ('avg_blood_pressure', models.CharField(max_length=20)),
                ('avg_calories', models.FloatField()),
                ('avg_bmi', models.FloatField()),
                ('weight_change', models.FloatField()),
                ('overall_health_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='health_record',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='physical_record',
        ),
        migrations.DeleteModel(
            name='MonthlyRecord',
        ),
        migrations.AddField(
            model_name='healthrecords',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='physicalrecords',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='physicalrecords',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='physical_records',
            field=models.ManyToManyField(blank=True, to='api.physicalrecords'),
        ),
        migrations.DeleteModel(
            name='DailyRecord',
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.user'),
        ),
    ]
