# Generated by Django 4.1.13 on 2024-07-16 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_report_remove_dailyrecord_health_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecords',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='physicalrecords',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
