# Generated by Django 4.1.13 on 2024-07-21 06:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_healthrecords_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_glucose', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('bmi', models.FloatField()),
                ('weight', models.FloatField()),
                ('diabetes_risk', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress_level', models.IntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('physical_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.physicalactivity')),
            ],
        ),
        migrations.RemoveField(
            model_name='physicalrecords',
            name='physical_activity',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='health_records',
        ),
        migrations.RemoveField(
            model_name='user',
            name='physical_records',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferences',
        ),
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meal',
            name='fats',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='fiber',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealrecommendation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mealrecommendation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meal_recommendations', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferences',
            name='allergies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='preferences',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='preferences',
            name='daily_calories_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preferences',
            name='daily_calories_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preferences',
            name='diets_followed',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='preferences',
            name='meals_per_day',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='preferences',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='api.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HealthRecords',
        ),
        migrations.DeleteModel(
            name='PhysicalRecords',
        ),
        migrations.AddField(
            model_name='physicalrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_records', to='api.user'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='api.user'),
        ),
    ]
