# Generated by Django 4.1.13 on 2024-07-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_healthrecord_physicalrecord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='id',
        ),
    ]
