# Generated by Django 4.1.13 on 2024-07-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
