# Generated by Django 5.0.7 on 2024-07-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_blacklistedtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalrecord',
            name='time',
        ),
    ]
