# Generated by Django 5.0.7 on 2024-07-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_physicalrecord_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalrecord',
            name='physical_activity',
        ),
        migrations.AddField(
            model_name='physicalrecord',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='physicalrecord',
            name='type',
            field=models.CharField(choices=[('Gym', 'Gym'), ('Daily Work', 'Daily Work'), ('Cardio', 'Cardio'), ('Yoga', 'Yoga'), ('Running', 'Running'), ('Dance', 'Dance')], default='Gym', max_length=50),
        ),
        migrations.AlterField(
            model_name='physicalrecord',
            name='stress_level',
            field=models.IntegerField(choices=[(0, 'No Stress'), (1, 'Low'), (2, 'Mild'), (3, 'Moderate'), (4, 'High'), (5, 'Very High'), (6, 'Severe'), (7, 'Max Stress')]),
        ),
        migrations.DeleteModel(
            name='PhysicalActivity',
        ),
    ]
