# Generated by Django 5.0.7 on 2024-07-31 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_physicalrecord_physical_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='nutrients',
        ),
    ]
