# Generated by Django 5.0.7 on 2024-07-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_meal_nutrients'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cholesterol',
            field=models.FloatField(default=0.0),
        ),
    ]
