# Generated by Django 5.0.7 on 2024-08-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_meal_cholesterol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalrecord',
            name='stress_level',
            field=models.IntegerField(blank=True, choices=[(0, 'No Stress'), (1, 'Low'), (2, 'Mild'), (3, 'Moderate'), (4, 'High'), (5, 'Very High'), (6, 'Severe'), (7, 'Max Stress')], null=True),
        ),
        migrations.AlterField(
            model_name='physicalrecord',
            name='type',
            field=models.CharField(blank=True, choices=[('Gym', 'Gym'), ('Daily Work', 'Daily Work'), ('Cardio', 'Cardio'), ('Yoga', 'Yoga'), ('Running', 'Running'), ('Dance', 'Dance')], default='Gym', max_length=50, null=True),
        ),
    ]
