# Generated by Django 5.0.7 on 2024-08-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_physicalrecord_stress_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='max_cholesterol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preferences',
            name='max_fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preferences',
            name='max_fiber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preferences',
            name='max_protein',
            field=models.IntegerField(default=0),
        ),
    ]
