# Generated by Django 5.0.7 on 2024-08-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_preferences_max_cholesterol_preferences_max_fat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='daily_calories_min',
        ),
    ]
