# Generated by Django 5.0.7 on 2024-08-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_preferences_daily_calories_min'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preferences',
            new_name='Customizations',
        ),
    ]
