# Generated by Django 5.0.7 on 2024-08-03 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_preferences_customizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizations',
            name='max_carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customizations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='api.user'),
        ),
    ]
