# Generated by Django 5.0.7 on 2024-08-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_customizations_max_carbs_alter_customizations_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizations',
            name='allergies',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='customizations',
            name='diets_followed',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='customizations',
            name='meals_per_day',
            field=models.JSONField(default=[]),
        ),
    ]
