# Generated by Django 5.0.7 on 2024-08-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_customizations_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizations',
            name='allergies',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='customizations',
            name='diets_followed',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='customizations',
            name='meals_per_day',
            field=models.JSONField(default=list),
        ),
    ]
