# Generated by Django 5.0.7 on 2024-08-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_customizations_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizations',
            name='daily_calories_max',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='customizations',
            name='max_carbs',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='customizations',
            name='max_cholesterol',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='customizations',
            name='max_fat',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='customizations',
            name='max_fiber',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='customizations',
            name='max_protein',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='blood_glucose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='blood_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalrecord',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
