# Generated by Django 5.0.7 on 2024-08-07 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_user_otp_user_otp_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('fiber', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('carbs', models.FloatField()),
                ('low_fat', models.BooleanField(default=False)),
                ('low_carb', models.BooleanField(default=False)),
                ('high_protein', models.BooleanField(default=False)),
                ('no_sugar', models.BooleanField(default=False)),
                ('wheat_free', models.BooleanField(default=False)),
                ('egg_free', models.BooleanField(default=False)),
                ('soy_free', models.BooleanField(default=False)),
                ('image_url', models.URLField(max_length=1024)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='mealrecommendation',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='mealrecommendation',
            name='recommendations',
            field=models.ManyToManyField(related_name='meal_recommendations', to='api.recommendation'),
        ),
    ]
