# Generated by Django 5.0.7 on 2024-08-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_recommendation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='image_url',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='image',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recipe',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MealRecommendation',
        ),
    ]
