# Generated by Django 5.0.7 on 2024-08-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_recommendation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='image',
            field=models.CharField(max_length=355),
        ),
    ]
