# Generated by Django 5.0.7 on 2024-08-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_recommendation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='image',
            field=models.ImageField(upload_to='recommendations_images/'),
        ),
    ]
