# Generated by Django 5.0.7 on 2024-08-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='total_calories',
            field=models.FloatField(default=0),
        ),
    ]
