# Generated by Django 5.0.7 on 2024-08-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_recommendation_total_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizations',
            name='max_cholesterol',
        ),
    ]
