# Generated by Django 5.0.7 on 2024-08-15 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_customizations_max_cholesterol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizations',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='physicalrecord',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
