# Generated by Django 5.0.7 on 2024-08-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_customizations_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizations',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='physicalrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
