# Generated by Django 5.0.7 on 2024-08-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_customizations_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
