# Generated by Django 5.0.7 on 2024-08-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_customizations_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='physicalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
